version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily
  reviewers:
  - swaglive/sre
- package-ecosystem: docker
  directory: /
  schedule:
    interval: daily
  reviewers:
  - swaglive/sre
