name: Docker

on:
  push:
    branches:
    - master
    tags:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      PLATFORMS: linux/amd64, linux/arm64/v8

    strategy:
      matrix:
        version:
        - "1.25.3-alpine"
        modules:
        - "auth-spnego brotli encrypted-session fips-check geoip geoip2 headers-more image-filter lua modsecurity ndk njs opentracing passenger perl rtmp set-misc subs-filter xslt"

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure
      id: config
      run: |-
        NPROC=$(nproc)

        echo "NPROC=$((NPROC*2+1))" >> $GITHUB_ENV
        echo "NPROC=$((NPROC*2+1))" >> $GITHUB_OUTPUT

        echo "image-owner=${{ github.repository_owner }}" >> $GITHUB_OUTPUT
        echo "image-name=${GITHUB_REPOSITORY#*/docker-}" >> $GITHUB_OUTPUT

    - name: Setup - QEMU
      id: qemu
      uses: docker/setup-qemu-action@v3
      with:
        platforms: ${{ env.PLATFORMS }}

    - name: Setup - buildx
      uses: docker/setup-buildx-action@v3
      with:
        platforms: ${{ steps.setup-qemu.outputs.platforms }}

    - name: Setup - Docker Hub
      uses: docker/login-action@v3
      if: ${{ github.ref_name == 'master' }}
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Setup - Github Container Registry
      uses: docker/login-action@v3
      if: ${{ github.ref_name == 'master' }}
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Setup - Docker image metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |-
          ${{ steps.config.outputs.image-owner }}/${{ steps.config.outputs.image-name }}
          ghcr.io/${{ steps.config.outputs.image-owner }}/${{ steps.config.outputs.image-name }}
        flavor: |-
          latest=${{ !!matrix.latest }}
        tags: |-
          type=semver,pattern={{major}}.{{minor}},value=${{ matrix.version }}
          type=semver,pattern={{major}}.{{minor}}.{{patch}},value=${{ matrix.version }}

    - name: Build
      uses: docker/build-push-action@v5
      id: build
      with:
        context: modules
        file: modules/Dockerfile.alpine
        build-args: |
          base=nginx:${{ matrix.version }}
          ENABLED_MODULES=ndk ${{ matrix.modules }}
        push: true
        platforms: ${{ env.PLATFORMS }}
        labels: ${{ steps.meta.outputs.labels }}
        tags: ${{ steps.meta.outputs.tags }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
